version: '3'

services:
  cobot-slack:
    image: cobot-slack
    build: .
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/data/app
    environment:
      HUBOT_JENKINS_URL: "${HUBOT_JENKINS_URL}"
      HUBOT_JENKINS_AUTH: "${HUBOT_JENKINS_AUTH}"
      HUBOT_SLACK_TOKEN: "${HUBOT_SLACK_TOKEN}"
      HUBOT_GIPHY_API_KEY: "${HUBOT_GIPHY_API_KEY}"
    ports:
      - "80:80"
    networks: ['jenkins_network']
networks: 
  jenkins_network:
    external:
      name: local-environment_provisioning